### ISSUE TITLE
user pass on the live demo dont work

### ISSUE THREAD

**Issue by rudygt** [vaadin-learning-center/crm-tutorial#137]

**Comment by lukislama** [comment]
Username should be "user" and the password "userpass" unless you changed this part of the code:

https://github.com/vaadin/flow-crm-tutorial/blob/27e5c0392fbfc2875bf04b4c85a8f134e26b0543/src/main/java/com/example/application/security/SecurityConfig.java#L20-L26

**Comment by rudygt** [comment]
Hello thanks for your answer, I was specifically talking about the live demo website 

![image](https://user-images.githubusercontent.com/1120692/221428117-7be63796-a06c-4f7e-80c1-706dfdfd61ef.png)

https://crm.demo.vaadin.com/login

**Comment by lukislama** [comment]
Oh yeah, I get it now. This seems to be an ongoing issue. Someone from the development team should re-deploy it. But I don't think that this it is that much of a priority for them. Since the system is open to everyone, someone will probably break it for fun eventually anyway.

**Comment by gmerton-amazon** [comment]
Agree that it would be cool if we could login to the live demo

**Comment by mshabarov** [comment]
user/userpass works, just checked.
admin/adminpass doesn't work.

**Comment by FlocusOnline** [comment]
> user/userpass works, just checked. admin/adminpass doesn't work.

still not working for me, although it did a while back. There is clearly an issue

**Comment by vaithu** [comment]
Yep same issue 
![image](https://github.com/vaadin/flow-crm-tutorial/assets/35440074/cba3fd23-022c-49a6-b9c1-ef5257f3fe7f)

**Comment by mshabarov** [comment]
Thanks everyone who commented, we'll try to get it fixed soon.

**Comment by mshabarov** [comment]
This should be fixed now, just tested with user/userpass.

Please create a new ticket if you notice that the login process is broken again.
