### ISSUE TITLE
SecurityConfig.java - 'authorizeHttpRequests()' is deprecated and marked for removal

### ISSUE THREAD

**Issue by trucke** [vaadin-learning-center/crm-tutorial#161]
Hey guys,

Want to check if this is already on your list. The method will also be removed in a future version.
I am using openJDK 17, the latest version of IntelliJ (2023.1.3) and the latest Spring Security version.

This point is also stated in the Spring migration guide, [Spring Security](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#use-new-requestmatchers).

Based on this guide the call should be changed to:
```java
http.authorizeHttpRequests((authz) -> authz
                .requestMatchers("/images/*.png").permitAll());
```

**Comment by mcollovati** [comment]
Hi, thanks for the issue.

Here's the issue on Flow repo https://github.com/vaadin/flow/issues/16872

And the PR, that is currently under review https://github.com/vaadin/flow/pull/17136
