### ISSUE TITLE
Logout doesn't work as it should be 

### ISSUE THREAD

**Issue by madukan** [vaadin-learning-center/crm-tutorial#172]
ie: You can logout from the view, it seem to take you to the link that say login with Keycloak. 
However, if you directly hit the URL of the dashboard, for instance, http://<host:port>/dashboard, the user doesn't really need to login again. This is a serious security flow.

**Comment by madukan** [comment]
I can see in the v24 logout works fine also. Let me test further.
So far, I logged out, and then tried to access dashboard, which as expected prompted me back to the login, which is good.
Therefore now no issue, in v24.

**Comment by Mikaelsu** [comment]
Hey! I cannot reproduce the issue. Which branch (which Vaadin version) were you testing it on?

**Comment by mshabarov** [comment]
@madukan thanks for the issue! Is there something extra on top of CRM tutorial codes that you use and see the issue? Or is it a purely CRM app with no extra codes?

**Comment by madukan** [comment]
Now that's a good question -- That reminds me I was integrating with Keycloak for the first version, I reverted all that and found the issue, the issue first happen. Let me try to dig a bit more on that. Once it worked I cleaned up all the non-working code off which is going to be a bit tricky trying to pull back from the bin now.

**Comment by mshabarov** [comment]
I couldn't reproduce this with Vaadin `24.1.8`, neither with `23.3.22`. The app always redirects me to the login view even if I hit the URL directly.

**Comment by mshabarov** [comment]
Closed because of no reply from author. Please comment in this ticket or create a new one if this issue is still valid for you.
