### ISSUE TITLE
gitpod run doesn't run

### ISSUE THREAD

**Issue by jflamy** [vaadin-learning-center/crm-tutorial#7]
Just deploying the master branch on gitpod doesn't work (I simply used the gitpod extension on the github page).  The program magically starts logging in a console window (I'll have to figure that one out), and finishes with
```
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
2020-04-29 20:14:39.097  INFO 1638 --- [nio-8080-exec-1] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
```
Opening the preview window or the browser for port 8080 yields "port 8080 didn't respond"

**Comment by marcushellberg** [comment]
Sorry. I only just saw this. Can you try it again, I made some changes to the gitpod setup to make it more reliable.

**Comment by marcushellberg** [comment]
Closing as it's working for me. Feel free to open a new one if you are still having issues
