### ISSUE TITLE
Odd usability when navigating away from unsaved form

### ISSUE THREAD

**Issue by emarc** [vaadin-learning-center/crm-tutorial#8]
If you change a record (contact) then open another contact w/o saving, the changes are not saved, but not cancelled either – if you navigate back to the changed record, it still has the changes you made visible in the form. This leads to a somewhat confusing UX. 
Video: https://d.pr/v/y1NXyo

Ideally it would require explicit action (save/cancel): disallow navigating away if the form has been modified, and make buttons indicate whether or not there are changes to save/cancel.

**Comment by marcushellberg** [comment]
fixed
